# Generated by Django 5.0.1 on 2025-11-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_hold_until_payment_is_wallet_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumpayment',
            name='payment_type',
            field=models.CharField(choices=[('boost', 'Profile Boost'), ('featured', 'Featured Listing'), ('premium', 'Premium Package'), ('subscription', 'Study Materials Subscription')], max_length=20),
        ),
    ]
