# Generated by Django 5.0.1 on 2025-11-12 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bio', models.TextField(help_text='Tell students about yourself')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='tutor_videos/')),
                ('profile_complete', models.BooleanField(default=False)),
                ('teaching_levels', models.CharField(choices=[('primary', 'Primary (1-5)'), ('middle', 'Middle (6-8)'), ('secondary', 'Secondary (9-10)'), ('senior_secondary', 'Senior Secondary (11-12)'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('all', 'All Levels')], default='all', max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('service_areas', models.TextField(blank=True, help_text='Comma-separated list of pincodes or areas')),
                ('is_available_online', models.BooleanField(default=True)),
                ('is_available_home', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('subjects', models.ManyToManyField(related_name='tutors', to='tutors.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutor Profile',
                'verbose_name_plural': 'Tutor Profiles',
            },
        ),
        migrations.CreateModel(
            name='TutorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('academic', 'Academic Certificate'), ('id_proof', 'ID Proof'), ('police_verification', 'Police Verification'), ('other', 'Other')], max_length=30)),
                ('document_file', models.FileField(upload_to='tutor_documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tutors.tutorprofile')),
            ],
            options={
                'verbose_name': 'Tutor Document',
                'verbose_name_plural': 'Tutor Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('home', 'Home Tutoring')], max_length=20)),
                ('level', models.CharField(blank=True, choices=[('primary', 'Primary'), ('middle', 'Middle'), ('secondary', 'Secondary'), ('senior_secondary', 'Senior Secondary'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='tutors.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='tutors.tutorprofile')),
            ],
            options={
                'verbose_name': 'Pricing Option',
                'verbose_name_plural': 'Pricing Options',
                'unique_together': {('tutor', 'subject', 'mode', 'level')},
            },
        ),
    ]
