# Generated by Django 5.0.1 on 2025-11-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='max_travel_distance',
            field=models.IntegerField(default=10, help_text='Maximum travel distance in km for home tutoring'),
        ),
    ]
