# Generated by Django 5.0.1 on 2025-11-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_tutorprofile_latitude_tutorprofile_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='List of professional certifications'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='has_academic_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='has_background_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='has_id_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='has_police_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutordocument',
            name='document_type',
            field=models.CharField(choices=[('academic', 'Academic Certificate'), ('id_proof', 'ID Proof'), ('police_verification', 'Police Verification'), ('certification', 'Professional Certification'), ('other', 'Other')], max_length=30),
        ),
    ]
