# Generated by Django 5.0.1 on 2025-11-12 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_tutorprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='boost_count',
            field=models.IntegerField(default=0, help_text='Number of times profile has been boosted'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured tutor listing'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='premium_boost_until',
            field=models.DateTimeField(blank=True, help_text='Premium boost expiration', null=True),
        ),
        migrations.CreateModel(
            name='PremiumSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_type', models.CharField(choices=[('boost', 'Profile Boost'), ('featured', 'Featured Listing'), ('premium', 'Premium Package')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_subscriptions', to='tutors.tutorprofile')),
            ],
            options={
                'verbose_name': 'Premium Subscription',
                'verbose_name_plural': 'Premium Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
