# Generated by Django 5.0.1 on 2025-11-12 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_tutorprofile_boost_count_tutorprofile_is_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='intervention_required',
            field=models.BooleanField(default=False, help_text='Requires admin intervention'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='last_quality_audit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='quality_issues',
            field=models.TextField(blank=True, help_text='Identified quality issues'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Overall quality score (0-100)', max_digits=5),
        ),
        migrations.CreateModel(
            name='QualityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_type', models.CharField(choices=[('automated', 'Automated Audit'), ('manual', 'Manual Review'), ('complaint', 'Complaint-Based'), ('scheduled', 'Scheduled Audit')], max_length=20)),
                ('quality_score', models.DecimalField(decimal_places=2, help_text='Quality score (0-100)', max_digits=5)),
                ('issues_found', models.TextField(blank=True, help_text='Issues identified during audit')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for improvement')),
                ('is_resolved', models.BooleanField(default=False)),
                ('audited_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['city_admin', 'global_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_conducted', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_audits', to='tutors.tutorprofile')),
            ],
            options={
                'verbose_name': 'Quality Audit',
                'verbose_name_plural': 'Quality Audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification_type', models.CharField(choices=[('excellent', 'Excellent Quality'), ('verified', 'Verified Quality'), ('premium', 'Premium Quality')], max_length=20)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['city_admin', 'global_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_issued', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_certifications', to='tutors.tutorprofile')),
            ],
            options={
                'verbose_name': 'Quality Certification',
                'verbose_name_plural': 'Quality Certifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
