# Generated by Django 5.0.1 on 2025-11-12 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_name', models.CharField(blank=True, max_length=100)),
                ('student_age', models.IntegerField(blank=True, null=True)),
                ('grade_level', models.CharField(blank=True, choices=[('primary', 'Primary (1-5)'), ('middle', 'Middle (6-8)'), ('secondary', 'Secondary (9-10)'), ('senior_secondary', 'Senior Secondary (11-12)'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], max_length=30)),
                ('preferred_mode', models.CharField(choices=[('online', 'Online'), ('home', 'Home Tutoring'), ('both', 'Both')], default='both', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('learning_goals', models.TextField(blank=True, help_text='What do you want to achieve?')),
                ('preferred_subjects', models.ManyToManyField(blank=True, related_name='interested_students', to='tutors.subject')),
                ('user', models.OneToOneField(limit_choices_to={'role__in': ['student', 'parent']}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
    ]
