# Generated by Django 5.0.1 on 2025-11-12 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.CharField(choices=[('tutor_rating', 'Tutor Average Rating'), ('booking_conversion', 'Booking Conversion Rate'), ('student_retention', 'Student Retention Rate'), ('revenue', 'Revenue'), ('commission', 'Commission Collected')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Performance Metric',
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['-period_start', 'metric_type'],
            },
        ),
        migrations.CreateModel(
            name='RevenueForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forecast_date', models.DateField()),
                ('forecasted_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence_level', models.DecimalField(decimal_places=2, help_text='Confidence level as percentage', max_digits=5)),
                ('factors', models.JSONField(blank=True, default=dict, help_text='Factors influencing the forecast')),
            ],
            options={
                'verbose_name': 'Revenue Forecast',
                'verbose_name_plural': 'Revenue Forecasts',
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='TrendAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trend_type', models.CharField(choices=[('user_growth', 'User Growth'), ('booking_trend', 'Booking Trend'), ('revenue_trend', 'Revenue Trend'), ('tutor_growth', 'Tutor Growth'), ('subject_popularity', 'Subject Popularity')], max_length=30)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('trend_data', models.JSONField(default=dict, help_text='Trend data points')),
                ('analysis', models.TextField(blank=True, help_text='Analysis and insights')),
            ],
            options={
                'verbose_name': 'Trend Analysis',
                'verbose_name_plural': 'Trend Analyses',
                'ordering': ['-period_start', 'trend_type'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('tutor_search', 'Tutor Search'), ('booking_created', 'Booking Created'), ('payment_completed', 'Payment Completed'), ('review_submitted', 'Review Submitted'), ('message_sent', 'Message Sent')], max_length=30)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='analytics_a_event_t_002468_idx'), models.Index(fields=['user', '-created_at'], name='analytics_a_user_id_157d89_idx')],
            },
        ),
    ]
