# Generated by Django 5.0.1 on 2025-11-12 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_is_recurring_booking_parent_booking_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='moderated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['city_admin', 'global_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(help_text='Review comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('booking', 'student')},
        ),
        migrations.CreateModel(
            name='ContentModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('profile', 'Profile'), ('message', 'Message'), ('review', 'Review'), ('document', 'Document')], max_length=20)),
                ('content_id', models.IntegerField()),
                ('reason', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_content', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['city_admin', 'global_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Moderation',
                'verbose_name_plural': 'Content Moderation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispute_type', models.CharField(choices=[('payment', 'Payment Issue'), ('service', 'Service Quality'), ('cancellation', 'Cancellation/Refund'), ('safety', 'Safety Concern'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Describe the issue')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='bookings.booking')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['city_admin', 'global_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('harassment', 'Harassment'), ('inappropriate_behavior', 'Inappropriate Behavior'), ('safety_concern', 'Safety Concern'), ('fraud', 'Fraud/Suspicious Activity'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(help_text='Describe the incident')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='safety_reports/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=30)),
                ('investigation_notes', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('investigated_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['city_admin', 'global_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_reports', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_reports_made', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_reports_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safety Report',
                'verbose_name_plural': 'Safety Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
